version: '3.8'
name: kuuweb

services:
  kuu-bot:
    image: kuu-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 6543:6543
    depends_on:
      db-migrate:
        condition: service_completed_successfully
  db-migrate:
    image: node:20.0-alpine
    working_dir: /app
    volumes:
      - ./.env:/app/.env
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./drizzle:/app/drizzle
      - ./src/database/schemas:/app/src/database/schemas
      - ./src/global.d.ts:/app/src/global.d.ts
      - ./tsconfig.json:/app/tsconfig.json
    command: sh -c "corepack enable && pnpm install && pnpm run migrate"
